# Generated by Django 5.2.12 on 2026-03-29 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='image',
            field=models.CharField(max_length=255),
        ),
    ]
